// 头像：提醒节奏、圆形取景框的裁剪计算、上传，以及界面文案。

import { extractFrappeError } from "./passkeyCheckin.js"

export const PHOTO_OUTPUT_SIZE = 512
export const PHOTO_MIN_SIDE = 128
export const PHOTO_MAX_ZOOM = 4
export const PHOTO_STATUS_METHOD = "hrms.api.profile_photo.get_profile_photo_status"
export const PHOTO_UPLOAD_METHOD = "hrms.api.profile_photo.upload_my_photo"

const COPY = {
	// 提醒正文是 HR 给的原话（2026-09-29），{0} 是截止日，{1} 是截止日第二天
	titleChange: { zh: "请更换头像", ja: "プロフィール画像の変更", en: "Change Your Profile Photo" },
	titleSet: { zh: "请设置头像", ja: "プロフィール画像の設定", en: "Set Your Profile Photo" },
	leadChange: {
		zh: "因系统更新，自{1}起，登录需使用您自行设置的头像。当前头像为系统临时生成，请最迟于{0}完成更换。逾期将暂时无法登录。给您带来不便，敬请谅解。",
		ja: "システム更新により、{1}以降のログインには、ご自身で設定したプロフィール画像が必要になります。現在の画像はシステムが仮に生成したものです。{0}までに変更をお願いいたします。未変更の場合、一時的にログインできなくなります。ご不便をおかけしますが、ご理解のほどお願いいたします。",
		en: "Due to a system update, from {1} you will need a profile photo you set yourself to log in. Your current photo is a temporary one generated by the system. Please change it by {0}. Otherwise you may temporarily be unable to log in. Sorry for the inconvenience.",
	},
	leadSet: {
		zh: "因系统更新，自{1}起，登录需使用您自行设置的头像。请最迟于{0}完成设置。逾期将暂时无法登录。给您带来不便，敬请谅解。",
		ja: "システム更新により、{1}以降のログインには、ご自身で設定したプロフィール画像が必要になります。{0}までに設定をお願いいたします。未設定の場合、一時的にログインできなくなります。ご不便をおかけしますが、ご理解のほどお願いいたします。",
		en: "Due to a system update, from {1} you will need a profile photo you set yourself to log in. Please set one by {0}. Otherwise you may temporarily be unable to log in. Sorry for the inconvenience.",
	},
	leadChangeNoDate: {
		zh: "因系统更新，登录需使用您自行设置的头像。当前头像为系统临时生成，请尽快完成更换。给您带来不便，敬请谅解。",
		ja: "システム更新により、ログインにはご自身で設定したプロフィール画像が必要になります。現在の画像はシステムが仮に生成したものです。早めに変更をお願いいたします。ご不便をおかけしますが、ご理解のほどお願いいたします。",
		en: "Due to a system update, you will need a profile photo you set yourself to log in. Your current photo is a temporary one generated by the system. Please change it soon. Sorry for the inconvenience.",
	},
	leadSetNoDate: {
		zh: "因系统更新，登录需使用您自行设置的头像。请尽快完成设置。给您带来不便，敬请谅解。",
		ja: "システム更新により、ログインにはご自身で設定したプロフィール画像が必要になります。早めに設定をお願いいたします。ご不便をおかけしますが、ご理解のほどお願いいたします。",
		en: "Due to a system update, you will need a profile photo you set yourself to log in. Please set one soon. Sorry for the inconvenience.",
	},
	takePhoto: { zh: "拍一张", ja: "写真を撮る", en: "Take a Photo" },
	choosePhoto: { zh: "从相册选择", ja: "アルバムから選ぶ", en: "Choose from Library" },
	later: { zh: "稍后再说", ja: "あとで", en: "Later" },
	cancel: { zh: "取消", ja: "キャンセル", en: "Cancel" },
	changeTitle: { zh: "更换头像", ja: "プロフィール画像の変更", en: "Change Photo" },
	changeLead: {
		zh: "请选一张照片作为头像。",
		ja: "プロフィール画像にする写真を選んでください。",
		en: "Choose a photo for your profile.",
	},
	editTitle: { zh: "调整头像", ja: "画像の調整", en: "Adjust Your Photo" },
	editHint: {
		zh: "拖动照片调整位置，双指或拖动滑块缩放",
		ja: "ドラッグで位置を、ピンチかスライダーで大きさを調整できます",
		en: "Drag to move. Pinch or use the slider to zoom.",
	},
	zoom: { zh: "缩放", ja: "拡大・縮小", en: "Zoom" },
	usePhoto: { zh: "使用这张", ja: "この写真を使う", en: "Use This Photo" },
	chooseAgain: { zh: "重新选择", ja: "選び直す", en: "Choose Another" },
	uploading: { zh: "正在上传…", ja: "アップロード中…", en: "Uploading…" },
	uploaded: {
		zh: "头像已更新",
		ja: "プロフィール画像を更新しました",
		en: "Profile photo updated",
	},
	readFailed: {
		zh: "无法读取这张照片，请换一张。",
		ja: "この写真を読み込めませんでした。別の写真を選んでください。",
		en: "This photo could not be opened. Please choose another one.",
	},
	tooSmall: {
		zh: "照片太小了，请换一张更清晰的。",
		ja: "写真が小さすぎます。もっと鮮明な写真を選んでください。",
		en: "This photo is too small. Please choose a clearer one.",
	},
	uploadFailed: {
		zh: "上传失败，请重试。",
		ja: "アップロードに失敗しました。もう一度お試しください。",
		en: "Upload failed. Please try again.",
	},
	cardTitleChange: {
		zh: "请更换头像",
		ja: "プロフィール画像を変更してください",
		en: "Change Your Profile Photo",
	},
	cardTitleSet: {
		zh: "还没有设置头像",
		ja: "プロフィール画像が未設定です",
		en: "No Profile Photo Yet",
	},
	cardDeadlineChange: {
		zh: "当前头像为系统临时生成，请在{0}前更换。",
		ja: "現在の画像は仮のものです。{0}までに変更してください。",
		en: "Your current photo is temporary. Please change it by {0}.",
	},
	cardDeadlineSet: {
		zh: "请在{0}前设置。",
		ja: "{0}までに設定してください。",
		en: "Please set one by {0}.",
	},
	cardOverdueChange: {
		zh: "当前头像为系统临时生成，已过更换期限（{0}），请尽快更换。",
		ja: "現在の画像は仮のものです。期限（{0}）を過ぎていますので、早めに変更してください。",
		en: "Your current photo is temporary and the deadline ({0}) has passed. Please change it soon.",
	},
	cardOverdueSet: {
		zh: "已过截止日期（{0}），请尽快设置。",
		ja: "期限（{0}）を過ぎています。早めに設定してください。",
		en: "The deadline ({0}) has passed. Please set one soon.",
	},
	cardNoDeadlineChange: {
		zh: "当前头像为系统临时生成，请尽快更换。",
		ja: "現在の画像は仮のものです。早めに変更してください。",
		en: "Your current photo is temporary. Please change it soon.",
	},
	cardNoDeadlineSet: {
		zh: "请设置一张头像。",
		ja: "プロフィール画像を設定してください。",
		en: "Please set a profile photo.",
	},
	cardActionChange: { zh: "去更换", ja: "変更する", en: "Change Photo" },
	cardActionSet: { zh: "去设置", ja: "設定する", en: "Set Photo" },
}

const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

export function pickPhotoCopy(key, lang = "zh", ...args) {
	const entry = COPY[key] || {}
	const text = entry[lang] || entry.zh || ""
	return args.reduce((result, value, index) => result.replace(`{${index}}`, value), text)
}

export function formatDeadline(value, lang = "zh") {
	const match = /^(\d{4})-(\d{2})-(\d{2})/.exec(String(value || ""))
	if (!match || Number(match[1]) < 2000) return ""
	const month = Number(match[2])
	const day = Number(match[3])
	return lang === "en" ? `${MONTHS[month - 1]} ${day}` : `${month}月${day}日`
}

// 有头像但不是自己上传的（HR 或脚本代设），就是临时头像
function isTemporary(status) {
	return status?.temporary ?? Boolean(status?.photo && !status?.has_photo)
}

export function nextDay(value) {
	const match = /^(\d{4})-(\d{2})-(\d{2})/.exec(String(value || ""))
	if (!match) return ""
	const date = new Date(Date.UTC(Number(match[1]), Number(match[2]) - 1, Number(match[3]) + 1))
	return date.toISOString().slice(0, 10)
}

export function getReminderContent(status, lang = "zh") {
	const kind = isTemporary(status) ? "Change" : "Set"
	const deadline = formatDeadline(status?.deadline, lang)
	const lead = deadline
		? pickPhotoCopy(`lead${kind}`, lang, deadline, formatDeadline(nextDay(status.deadline), lang))
		: pickPhotoCopy(`lead${kind}NoDate`, lang)
	return {
		title: pickPhotoCopy(`title${kind}`, lang),
		lead,
		overdue: Boolean(deadline && status?.overdue),
	}
}

export function getPromptCardContent(status, lang = "zh") {
	const kind = isTemporary(status) ? "Change" : "Set"
	const deadline = formatDeadline(status?.deadline, lang)
	const overdue = Boolean(deadline && status?.overdue)
	const message = deadline
		? pickPhotoCopy(`${overdue ? "cardOverdue" : "cardDeadline"}${kind}`, lang, deadline)
		: pickPhotoCopy(`cardNoDeadline${kind}`, lang)
	return {
		title: pickPhotoCopy(`cardTitle${kind}`, lang),
		message,
		action: pickPhotoCopy(`cardAction${kind}`, lang),
		overdue,
	}
}

function clamp(value, min, max) {
	return Math.min(Math.max(value, min), max) || 0
}

// 取景框是边长 viewport 的正方形（圆形遮罩），照片按 cover 铺满后再乘 zoom；
// x、y 是照片中心相对取景框中心的偏移（屏幕像素）。
function imageScale({ width, height, viewport, zoom }) {
	return (viewport / Math.min(width, height)) * zoom
}

export function clampOffset({ width, height, viewport, zoom, x, y }) {
	const scale = imageScale({ width, height, viewport, zoom })
	const maxX = Math.max(0, (width * scale - viewport) / 2)
	const maxY = Math.max(0, (height * scale - viewport) / 2)
	return { x: clamp(x, -maxX, maxX), y: clamp(y, -maxY, maxY) }
}

export function cropRect({ width, height, viewport, zoom, x, y }) {
	const size = Math.min(width, height) / zoom
	const imagePerScreen = size / viewport
	const sx = width / 2 - x * imagePerScreen - size / 2
	const sy = height / 2 - y * imagePerScreen - size / 2
	return { sx: clamp(sx, 0, width - size), sy: clamp(sy, 0, height - size), size }
}

export function maxZoomFor(width, height) {
	return Math.max(1, Math.min(PHOTO_MAX_ZOOM, Math.min(width, height) / PHOTO_MIN_SIDE))
}

export function outputSizeFor(cropSize) {
	return Math.max(PHOTO_MIN_SIDE, Math.min(PHOTO_OUTPUT_SIZE, Math.round(cropSize)))
}

export async function uploadProfilePhoto(
	blob,
	{
		fetchImpl = globalThis.fetch?.bind(globalThis),
		csrfToken = globalThis.window?.csrf_token,
	} = {}
) {
	const body = new FormData()
	body.append("file", blob, "profile-photo.jpg")
	const response = await fetchImpl(`/api/method/${PHOTO_UPLOAD_METHOD}`, {
		method: "POST",
		headers: { Accept: "application/json", "X-Frappe-CSRF-Token": csrfToken || "" },
		body,
		credentials: "same-origin",
	})
	let data = {}
	try {
		data = await response.json()
	} catch (_) {
		data = {}
	}
	const photo = data?.message?.photo
	if (!response.ok || !photo) {
		const error = new Error(extractFrappeError(data))
		error.status = response.status
		throw error
	}
	return photo
}
